### PR TITLE
fixed nav and responsiveness

### PR DESCRIPTION
**Pull request by hvrxicqne**

### CODE REVIEW

**Comment by ion05** [comment]
LGTM!
@yuvraajnarula should we merge?

**Comment by yuvraajnarula** [comment]
> LGTM
Things to work on(mobile pov): 
- Icons in member card
- Search bar on the member's page
- Buttons in intech event card

@hvrxicqne  fix these

**Comment by hvrxicqne** [comment]
> > LGTM
> > Things to work on(mobile pov):
> 
> * Icons in member card
> * Search bar on the member's page
> * Buttons in intech event card
> 
> @hvrxicqne fix these

fixed most of the problems for users with devices of res 360 * xyz height.

**Comment by ion05** [comment]
- Navbar doesnt close automatically when you go to another page 
- Y-axis scroll on all pages

**Comment by hvrxicqne** [comment]
Fixed some issues for mobile users. The navbar links now directly redirect to the website link (for mobile). Since the link changes, it resets the css properties. Also fixed the x axis scroll on mobile devices.

**Comment by gamer-1478** [comment]
@yuvraajnarula @ion05 this commit is merge-ready IMO.

**Comment by gamer-1478** [comment]
@hvrxicqne won't accept changes in data/members.json, deleting that

On top of that, won't recommend
- inline CSS for such a big project, keep it in mind for the next time. 
- changing image quality and decreasing the image size permanently. if u have a problem with the image, use CSS to fix its sizing.

**Review by gamer-1478 — CHANGES_REQUESTED** [review]
- don't edit the snowglobe, go back.
- remove the changes in members.json, do a git pull for the latest file. 
other changes are fine good work. don't use inline CSS from the next time.

**Review by gamer-1478 — APPROVED** [review]
lgtm

**Pull request merged**
